apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAiYXV0aCI6ICJSMlZ1YVc5MWN5MWhkanBuYUhCZlRVMUZZMnB0V2tOMk1Xc3hZVU00TUUxTFNGVTNWbkZFZVVwNFNsaEJNME5tUlhJNSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
